// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

export const lovable = {
  auth: {
    signInWithOAuth: async () => {
      return { error: new Error("Google sign-in is disabled") };
    },
  },
};
